### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by mohammed-elhaouari** [phpjuice/paypal#1]
## Tasks

- [ ] add paypal environment
- [ ] add paypal HTTP client
- [ ] add checkout API sdk
